final products = [
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Nike',
    'sizes': [6, 7, 8, 9, 10, 11, 12],
  },
  {
    'id': '1',
    'title': 'Addidas Shoes',
    'price': 20.12,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Addidas',
    'sizes': [6, 7, 8, 9, 10, 11, 12],
  },
  {
    'id': '2',
    'title': 'Bata Women\'s Shoes',
    'price': 28.95,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Bata',
    'sizes': [6, 7, 8, 9, 10, 11, 12],
  },
  {
    'id': '3',
    'title': 'Jordan Shoes',
    'price': 420.69,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Nike',
    'sizes': [6, 7, 8, 9, 10, 11, 12],
  },
  {
    'id': '8',
    'title': 'Nike\'s Air Jordan Shoes',
    'price': 420.69,
    'imageUrl': 'assets/images/shoes_9.png',
    'company': 'Nike',
    'sizes': [6, 7, 8, 9, 10, 11, 12],
  },
  {
    'id': '4',
    'title': 'Puma Shoes',
    'price': 180.69,
    'imageUrl': 'assets/images/shoes_5.png',
    'company': 'Puma',
    'sizes': [6, 7, 8, 9, 12],
  },
  {
    'id': '5',
    'title': 'Nike Ladies Sport Shoes',
    'price': 32.69,
    'imageUrl': 'assets/images/shoes_6.png',
    'company': 'Nike',
    'sizes': [6, 7, 8, 9, 10, 11, 12],
  },
  {
    'id': '6',
    'title': 'Sketcher\'s Shoes',
    'price': 20.69,
    'imageUrl': 'assets/images/shoes_7.png',
    'company': 'Sktecher',
    'sizes': [6, 7, 8, 9, 10, 11, 12],
  },
  {
    'id': '7',
    'title': 'Nike Running Shoes',
    'price': 10.69,
    'imageUrl': 'assets/images/shoes_8.png',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11, 12],
  },
  {
    'id': '8',
    'title': 'Puma Roma Shoes',
    'price': 399.69,
    'imageUrl': 'assets/images/shoes_10.png',
    'company': 'Puma',
    'sizes': [6, 7, 8, 9, 10, 11, 12],
  },
];